### PR TITLE
Can fixes AutoTLS

### LINKED ISSUE #30: "Let's Encrypt" | TLS-SNI challenge disabled
[Let's Encrypt has permanently disable the TLS-SNI challenge](https://community.letsencrypt.org/t/tls-sni-challenges-disabled-for-most-new-issuance/50316).

For what I see, `TLS-SNI` is the only way `Armor` and `Echo` can get certificates.

I tried to update `Echo` to use `HTTP-01` but it needs to use the other HTTP handler (port `80`).
This become a heavy work and I don't have the time to find a nice way to do it.

### PR DESCRIPTION
**Pull request by alexandreStein**
Fixes #30  and add support for custom ACME endpoint directory.

### CODE REVIEW

**Comment by alexandreStein** [comment]
Any reason why this is not merged?
Did you fixed it on an other commit?

**Comment by vishr** [comment]
I will review it today, it worked right?

**Comment by vishr** [comment]
@alexandreStein Somehow there was a merge conflict and I was not in a position to manually merge it. However, your changes are part of the latest release. I will take care of it from next time :). Thanks for your effort.

**Comment by alexandreStein** [comment]
All good, just wanted to know.

**Comment by vishr** [comment]
Cool, btw I like your code!

**Pull request closed without merging**
